// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEAZP37ZHKOFsZALsay3JiA1fA-ecFR_s',
    appId: '1:525833305880:web:4bff7a379052a72f12686d',
    messagingSenderId: '525833305880',
    projectId: 'complaintsportal-5de71',
    authDomain: 'complaintsportal-5de71.firebaseapp.com',
    storageBucket: 'complaintsportal-5de71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwX9B6V4d28pcGNZYpeX_9ukt9MoUEU9E',
    appId: '1:525833305880:android:29780bad76fe31cd12686d',
    messagingSenderId: '525833305880',
    projectId: 'complaintsportal-5de71',
    storageBucket: 'complaintsportal-5de71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4FtfmPkByxxydqnjlCVErU80oBRQDMII',
    appId: '1:525833305880:ios:92c721f7ce7c6b5812686d',
    messagingSenderId: '525833305880',
    projectId: 'complaintsportal-5de71',
    storageBucket: 'complaintsportal-5de71.appspot.com',
    iosBundleId: 'com.example.complaintsPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4FtfmPkByxxydqnjlCVErU80oBRQDMII',
    appId: '1:525833305880:ios:8a9c5d40456e9cc312686d',
    messagingSenderId: '525833305880',
    projectId: 'complaintsportal-5de71',
    storageBucket: 'complaintsportal-5de71.appspot.com',
    iosBundleId: 'com.example.complaintsPortal.RunnerTests',
  );
}
